service:
  type: ClusterIP
image:
  repository:
  pullPolicy:
  imagePullSecret:
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
securityContext:
  runAsUser:
  fsGroup:
statusCheck:
  initialDelay: 180
volume:
  storageClassName: manual
  storage: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
nextlabs:
  cc:
    caCertificate:
    oidc:
      clientSecret:
    url:
    policyValidatorDataVolumeClaimName:
